name: mamba executable debugging

on: [push, pull_request]

defaults:
  run:
    shell: bash -l {0}

jobs:
  test:
    name: mamba executables?
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v4

    - name: Set up conda environment with micromamba
      uses: mamba-org/setup-micromamba@v1
      with:
        environment-name: dude-wheres-my-snake
        create-args: >-
          python=${{ matrix.python-version }}
    
    - name: Look for micromamba
      run: |
        which -a micromamba
        micromamba --version
        micromamba list
    
    - name: Look for mamba
      run: |
        which -a mamba
        mamba --version
        mamba list
    