name: Short circuiting via saving a variable

on: [push, pull_request]

jobs:
  test:
    name: short circuit
    runs-on: ubuntu-latest
    steps:
      - name: Set var action_condition to true
        run: echo "action_condition=true" >> $GITHUB_ENV

      - name: Check value of action_condition
        if: ${{ env.action_condition == 'true' }}
        run: |
            echo "it is TRUE"

      - name: Set var action_condition to false 
        run: echo "action_condition=false" >> $GITHUB_ENV

      - name: Check value of action_condition
        if: ${{ env.action_condition == 'true' }}
        run: |
            echo "it is TRUE"
