name: Sleep

on:
  workflow_dispatch:

jobs:
  test:
    name: sleep tests
    runs-on: ubuntu-latest
    steps:
      - name: Sleep for 10 seconds
        run:
            sleep 10
    steps:
      - name: Sleep for 100 seconds
        run:
            sleep 100
    steps:
      - name: Sleep for 1000 seconds
        run:
            sleep 1000
    steps:
      - name: Sleep for 10000 seconds
        run:
            sleep 10000
    steps:
      - name: Sleep for 100000 seconds
        run:
            sleep 100000
