name: Exploration

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  test:
    name: event conditionals
    runs-on: ubuntu-latest
    steps:
      - name: Printing event name
        run: |
            echo "Hello ${{ github.event }}!"
